#!/usr/bin/env python3
"""Extracts annotations (highlights, notes) from PDF files and writes them out
as a Markdown table - one 'annotations.md' per directory, or everything
collected into a single file.

Standalone script: it needs nothing but Python 3.9+ and sets up its own virtual
environment with PyMuPDF on first run.

    ./pdf_annotations.py                        # PDFs in the current directory
    ./pdf_annotations.py ~/literature           # PDFs below some path
    ./pdf_annotations.py a.pdf b.pdf -o -       # single files to stdout
    ./pdf_annotations.py ~/literature --watch   # keep watching
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

__version__ = "1.1.0"

PROG = Path(__file__).stem
AUTO_MARKER = "<!-- generated by pdf_annotations.py - do not edit by hand -->"
OUTPUT_NAME = "annotations.md"
REQUIREMENT = "pymupdf>=1.24"
BOOTSTRAP_GUARD = "PDF_ANNOTS_BOOTSTRAPPED"

# Set by ensure_pymupdf() - not available until after the bootstrap.
pymupdf = None  # type: ignore[assignment]

# Annotation types we keep. Link/Popup/Widget are ignored because they are not
# reading notes (PDFs often carry hundreds of internal links).
TEXT_MARKUP = {"Highlight", "Underline", "StrikeOut", "Squiggly"}
REGION_MARKUP = {"Square", "Circle", "Ink", "Polygon", "PolyLine", "Caret"}
NOTE_ONLY = {"Text", "FreeText", "Stamp", "FileAttachment"}
WANTED = TEXT_MARKUP | REGION_MARKUP | NOTE_ONLY

TYPE_NAMES = {
    "Highlight": "highlight",
    "Underline": "underline",
    "StrikeOut": "strikeout",
    "Squiggly": "squiggly",
    "Text": "note",
    "FreeText": "text box",
    "Square": "box",
    "Circle": "ellipse",
    "Ink": "freehand",
    "Polygon": "polygon",
    "PolyLine": "polyline",
    "Caret": "caret",
    "Stamp": "stamp",
    "FileAttachment": "attachment",
}

COLOR_NAMES = {
    "yellow": (1.00, 0.92, 0.23),
    "orange": (1.00, 0.60, 0.00),
    "red": (0.95, 0.20, 0.20),
    "pink": (1.00, 0.40, 0.75),
    "purple": (0.60, 0.35, 0.85),
    "blue": (0.25, 0.50, 0.95),
    "cyan": (0.20, 0.80, 0.90),
    "green": (0.30, 0.80, 0.35),
    "gray": (0.55, 0.55, 0.55),
    "black": (0.00, 0.00, 0.00),
    "white": (1.00, 1.00, 1.00),
}


@dataclass
class Annotation:
    pdf: Path
    page: int
    section: str
    kind: str
    color: str
    quote: str
    note: str
    author: str
    date: str
    sort_y: float
    sort_x: float


# ---------------------------------------------------------------- Bootstrap


def venv_candidates(explicit: str = "") -> list[Path]:
    """Possible locations for the environment - in this order."""
    if explicit:
        return [Path(explicit).expanduser()]
    if os.environ.get("PDF_ANNOTS_VENV"):
        return [Path(os.environ["PDF_ANNOTS_VENV"]).expanduser()]
    here = Path(__file__).resolve().parent
    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return [here / ".venv", cache / "pdf-annots" / "venv"]


def venv_python(venv: Path) -> Path:
    return venv / ("Scripts" if os.name == "nt" else "bin") / ("python.exe" if os.name == "nt" else "python")


def has_pymupdf(python: Path) -> bool:
    try:
        return subprocess.run([str(python), "-c", "import pymupdf"],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
    except OSError:
        return False


def bootstrap(explicit: str = "") -> "Path | None":
    """Find or create an environment with PyMuPDF, return the interpreter path."""
    candidates = venv_candidates(explicit)
    for venv in candidates:
        python = venv_python(venv)
        if python.is_file() and has_pymupdf(python):
            return python

    venv = candidates[-1]
    python = venv_python(venv)
    if not python.is_file():
        print(f"[{PROG}] setting up Python environment in {venv} ...", file=sys.stderr)
        venv.parent.mkdir(parents=True, exist_ok=True)
        try:
            subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        except (subprocess.CalledProcessError, OSError) as exc:
            print(f"[{PROG}] could not create venv: {exc}", file=sys.stderr)
            return None
    print(f"[{PROG}] installing {REQUIREMENT} ...", file=sys.stderr)
    try:
        subprocess.run([str(python), "-m", "pip", "install", "--quiet", "--upgrade", "pip"], check=False)
        subprocess.run([str(python), "-m", "pip", "install", "--quiet", REQUIREMENT], check=True)
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"[{PROG}] installation failed: {exc}", file=sys.stderr)
        return None
    return python if has_pymupdf(python) else None


def ensure_pymupdf(allow_bootstrap: bool, explicit_venv: str = "") -> None:
    """Import PyMuPDF; if need be build an environment and restart in it."""
    global pymupdf
    try:
        import pymupdf as module  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        pymupdf = module
        return

    if not allow_bootstrap or os.environ.get(BOOTSTRAP_GUARD):
        sys.exit(f"[{PROG}] PyMuPDF is missing. Install it with: pip install '{REQUIREMENT}'")

    python = bootstrap(explicit_venv)
    if python is None:
        sys.exit(f"[{PROG}] PyMuPDF is missing and could not be installed. "
                 f"Do it manually: pip install '{REQUIREMENT}'")

    env = dict(os.environ, **{BOOTSTRAP_GUARD: "1"})
    os.execve(str(python), [str(python), str(Path(__file__).resolve()), *sys.argv[1:]], env)


# ---------------------------------------------------------------- Helpers


def color_name(rgb) -> str:
    if not rgb:
        return ""
    r, g, b = (float(c) for c in rgb[:3])
    best, best_d = "", None
    for name, (cr, cg, cb) in COLOR_NAMES.items():
        d = (r - cr) ** 2 + (g - cg) ** 2 + (b - cb) ** 2
        if best_d is None or d < best_d:
            best, best_d = name, d
    return best


def parse_pdf_date(value: str) -> str:
    """'D:20260907143000+02'00'' -> '2026-09-07 14:30'."""
    if not value:
        return ""
    m = re.match(r"D?:?(\d{4})(\d{2})?(\d{2})?(\d{2})?(\d{2})?", value.strip())
    if not m:
        return ""
    year, month, day, hour, minute = (m.group(i) or "" for i in range(1, 6))
    if not (month and day):
        return year
    stamp = f"{year}-{month}-{day}"
    if hour and minute:
        stamp += f" {hour}:{minute}"
    return stamp


def clean(text: str) -> str:
    # drop soft hyphens, expand fi/fl ligatures
    text = text.replace("­", "").replace("ﬁ", "fi").replace("ﬂ", "fl")
    text = re.sub(r"[ \t]+", " ", text.replace("\r", "\n"))
    return text.strip()


def md_cell(text: str, limit: int = 0) -> str:
    text = clean(text).replace("|", "\\|")
    text = re.sub(r"\s*\n\s*", " ", text)
    if limit and len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def area(rect) -> float:
    """Area of a rect - PyMuPDF has no stable API for this."""
    return max(0.0, rect.x1 - rect.x0) * max(0.0, rect.y1 - rect.y0)


def quads_of(annot) -> list:
    """Rectangles of the annotation - one per highlighted line of text."""
    try:
        verts = annot.vertices
    except Exception:
        verts = None
    rects = []
    if verts and annot.type[1] in TEXT_MARKUP and len(verts) >= 4:
        points = [p for p in verts if isinstance(p, (tuple, list)) and len(p) == 2]
        for i in range(0, len(points) - 3, 4):
            try:
                rects.append(pymupdf.Quad(points[i : i + 4]).rect)
            except Exception:
                continue
    if not rects:
        rects = [pymupdf.Rect(annot.rect)]
    return [r for r in rects if not r.is_empty]


def text_in_rects(words, rects) -> str:
    """Gather the words that lie mostly inside the rectangles."""
    picked: dict = {}
    for x0, y0, x1, y1, word, block, line, wno in words:
        wrect = pymupdf.Rect(x0, y0, x1, y1)
        warea = area(wrect)
        if warea <= 0:
            continue
        covered = 0.0
        for r in rects:
            inter = wrect & r
            if not inter.is_empty:
                covered += area(inter)
        if covered / warea >= 0.45:
            picked.setdefault((block, line), []).append((wno, word))

    lines = []
    for key in sorted(picked):
        lines.append(" ".join(w for _, w in sorted(picked[key])))

    out = ""
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if not out:
            out = line
        elif out.endswith("-"):
            out = out[:-1] + line
        else:
            out += " " + line
    return clean(out)


def build_sections(doc) -> list:
    """Table of contents as (page, y, title) - for the 'Section' column."""
    entries = []
    try:
        toc = doc.get_toc(simple=False)
    except Exception:
        toc = []
    for item in toc:
        title, page = item[1], item[2]
        if page is None or page < 1:
            continue
        y = 0.0
        if len(item) > 3 and isinstance(item[3], dict):
            point = item[3].get("to")
            if point is not None:
                try:
                    y = float(getattr(point, "y", 0.0))
                except Exception:
                    y = 0.0
        entries.append((int(page), y, clean(str(title))))
    # y is measured from the top - as with annot.rect - so sort ascending.
    entries.sort(key=lambda e: (e[0], e[1]))
    return entries


def section_for(entries, page: int, y: float) -> str:
    """Last outline entry above resp. before the annotation."""
    best = ""
    for p, ey, title in entries:
        if p > page:
            break
        if p < page or ey <= y + 2:
            best = title
    return best


# ---------------------------------------------------------------- Extraction


def extract(pdf: Path) -> list:
    doc = pymupdf.open(pdf)
    try:
        sections = build_sections(doc)
        found = []
        for page in doc:
            annots = list(page.annots()) if page.first_annot else []
            if not annots:
                continue
            words = page.get_text("words")
            for annot in annots:
                kind = annot.type[1]
                if kind not in WANTED:
                    continue
                info = annot.info or {}
                rects = quads_of(annot)
                quote = "" if kind in NOTE_ONLY else text_in_rects(words, rects)
                note = clean(info.get("content", ""))
                if not quote and not note and kind in REGION_MARKUP:
                    quote = text_in_rects(words, rects)
                if not quote and not note:
                    continue
                colors = annot.colors or {}
                rgb = colors.get("stroke") or colors.get("fill")
                top = min((r.y0 for r in rects), default=0.0)
                left = min((r.x0 for r in rects), default=0.0)
                found.append(
                    Annotation(
                        pdf=pdf,
                        page=page.number + 1,
                        section=section_for(sections, page.number + 1, top),
                        kind=TYPE_NAMES.get(kind, kind),
                        color=color_name(rgb),
                        quote=quote,
                        note=note,
                        author=clean(info.get("title", "")),
                        date=parse_pdf_date(info.get("modDate") or info.get("creationDate", "")),
                        sort_y=top,
                        sort_x=left,
                    )
                )
        return found
    finally:
        doc.close()


# ---------------------------------------------------------------- Output


def render(title: str, annots: list, with_author: bool, limit: int = 0,
           with_path: bool = False, base: "Path | None" = None) -> str:
    annots = sorted(annots, key=lambda a: (str(a.pdf).lower(), a.page, a.sort_y, a.sort_x))
    header = ["Source", "Page", "Section", "Type", "Color", "Highlight", "Note"]
    if with_author:
        header += ["Author", "Date"]

    def label(pdf: Path) -> str:
        if not with_path:
            return pdf.stem
        try:
            rel = pdf.relative_to(base) if base else pdf
        except ValueError:
            rel = pdf
        return rel.as_posix()[: -len(".pdf")] if rel.suffix.lower() == ".pdf" else rel.as_posix()

    rows = []
    for a in annots:
        row = [
            md_cell(label(a.pdf)),
            str(a.page),
            md_cell(a.section) or "-",
            a.kind,
            a.color or "-",
            md_cell(a.quote, limit) or "-",
            md_cell(a.note, limit) or "-",
        ]
        if with_author:
            row += [md_cell(a.author) or "-", a.date or "-"]
        rows.append(row)

    widths = [len(h) for h in header]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))

    def line(cells):
        return "| " + " | ".join(c.ljust(widths[i]) for i, c in enumerate(cells)) + " |"

    files = {a.pdf for a in annots}
    out = [
        f"# Annotations - {title}",
        "",
        AUTO_MARKER,
        "",
        f"{len(annots)} {plural(len(annots), 'annotation', 'annotations')} from "
        f"{len(files)} {plural(len(files), 'PDF file', 'PDF files')}.",
        "",
        line(header),
        "| " + " | ".join("-" * widths[i] for i in range(len(header))) + " |",
    ]
    out += [line(row) for row in rows]
    out.append("")
    return "\n".join(out)


def write_file(target: Path, content: str, dry_run: bool) -> str:
    if target.exists():
        old = target.read_text(encoding="utf-8", errors="replace")
        if old == content:
            return ""
        if AUTO_MARKER not in old:
            return f"SKIPPED  {target} exists and is not auto-generated"
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return f"wrote  {target}"


def write_per_directory(directory: Path, annots: list, opts) -> str:
    target = directory / opts.output_name

    if not annots:
        if target.exists() and AUTO_MARKER in target.read_text(encoding="utf-8", errors="replace"):
            if not opts.dry_run:
                target.unlink()
            return f"removed  {target} (no annotations left)"
        return ""

    content = render(directory.name or str(directory), annots, opts.with_author_date, opts.max_cell)
    msg = write_file(target, content, opts.dry_run)
    if msg.startswith("wrote"):
        msg += f"  ({len(annots)} {plural(len(annots), 'annotation', 'annotations')})"
    return msg


# ---------------------------------------------------------------- Scan / Watch


def is_hidden(path: Path, base: Path) -> bool:
    try:
        parts = path.relative_to(base).parts
    except ValueError:
        parts = path.parts
    return any(part.startswith(".") for part in parts)


def excluded(path: Path, base: Path, patterns: list) -> bool:
    try:
        rel = path.relative_to(base).as_posix()
    except ValueError:
        rel = path.as_posix()
    return any(fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(path.name, pat) for pat in patterns)


def find_pdfs(paths: list, excludes: list, recursive: bool = True) -> list:
    """PDFs below the given paths - files are taken as they are."""
    found = []
    seen = set()
    for path in paths:
        if path.is_file():
            candidates = [path] if path.suffix.lower() == ".pdf" else []
            base = path.parent
        else:
            base = path
            candidates = sorted(path.rglob("*.pdf") if recursive else path.glob("*.pdf"))
        for pdf in candidates:
            if pdf.is_dir() or is_hidden(pdf, base) or excluded(pdf, base, excludes):
                continue
            key = str(pdf.resolve())
            if key in seen:
                continue
            seen.add(key)
            found.append(pdf)
    return sorted(found, key=lambda p: str(p).lower())


def plural(n: int, one: str, many: str) -> str:
    return one if n == 1 else many


def stamp() -> str:
    return datetime.now().strftime("%H:%M:%S")


def collect(pdfs: list) -> list:
    annots = []
    for pdf in pdfs:
        try:
            annots.extend(extract(pdf))
        except Exception as exc:  # damaged file, or one being saved right now
            print(f"[{stamp()}] ERROR  {pdf}: {exc}", file=sys.stderr)
    return annots


def process(opts, quiet: bool = False) -> int:
    pdfs = find_pdfs(opts.paths, opts.excludes, opts.recursive)
    if not pdfs:
        if not quiet:
            print(f"[{stamp()}] no PDF files found", file=sys.stderr)
        return 0
    annots = collect(pdfs)

    # Collected output: a single file or stdout
    if opts.output is not None:
        base = opts.paths[0] if opts.paths[0].is_dir() else opts.paths[0].parent
        title = opts.title or (base.resolve().name or str(base))
        content = render(title, annots, opts.with_author_date, opts.max_cell,
                         with_path=True, base=base)
        if str(opts.output) == "-":
            sys.stdout.write(content)
            return 0
        msg = write_file(opts.output, content, opts.dry_run) or (
            "" if quiet else f"no changes  {opts.output}")
        if msg.startswith("wrote"):
            msg += f"  ({len(annots)} {plural(len(annots), 'annotation', 'annotations')})"
        if msg:
            print(f"[{stamp()}] {msg}")
        return 0

    # Default: one file per directory
    by_dir = {p.parent: [] for p in pdfs}
    for a in annots:
        by_dir[a.pdf.parent].append(a)

    changes = 0
    for directory in sorted(by_dir):
        msg = write_per_directory(directory, by_dir[directory], opts)
        if msg:
            changes += 1
            print(f"[{stamp()}] {msg}")
    if not changes and not quiet:
        print(f"[{stamp()}] no changes ({len(pdfs)} {plural(len(pdfs), 'PDF', 'PDFs')}, "
              f"{len(annots)} {plural(len(annots), 'annotation', 'annotations')})")
    return 0


def fingerprint(opts) -> dict:
    out = {}
    for pdf in find_pdfs(opts.paths, opts.excludes, opts.recursive):
        try:
            st = pdf.stat()
        except OSError:
            continue
        out[str(pdf)] = (st.st_mtime, st.st_size)
    return out


def watch(opts) -> None:
    where = ", ".join(str(p) for p in opts.paths)
    print(f"[{stamp()}] watching {where} (interval {opts.interval:g}s) - stop with Ctrl-C")
    state = fingerprint(opts)
    process(opts)
    while True:
        time.sleep(opts.interval)
        current = fingerprint(opts)
        if current == state:
            continue
        # Wait until the file has settled (Preview/Skim write in several steps)
        while True:
            time.sleep(min(opts.interval, 1.0))
            settled = fingerprint(opts)
            if settled == current:
                break
            current = settled
        added = set(current) - set(state)
        removed = set(state) - set(current)
        touched = {p for p in set(current) & set(state) if current[p] != state[p]}
        for label, items in (("new", added), ("gone", removed), ("changed", touched)):
            for item in sorted(items):
                print(f"[{stamp()}] {label}: {item}")
        state = current
        process(opts, quiet=True)


# ---------------------------------------------------------------- CLI


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=PROG,
        description="Write PDF annotations out as a Markdown table.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  %(prog)s.py ~/literature\n"
               "  %(prog)s.py ~/literature -o annotations.md\n"
               "  %(prog)s.py paper.pdf -o -\n"
               "  %(prog)s.py ~/literature --watch\n",
    )
    parser.add_argument("paths", nargs="*", type=Path, default=None,
                        help="directories and/or PDF files (default: current directory)")
    parser.add_argument("--root", type=Path, action="append", default=[],
                        help="additional root directory (legacy spelling for a positional argument)")
    parser.add_argument("-o", "--output", type=Path, default=None,
                        help="write everything into ONE Markdown file ('-' = stdout) "
                             "instead of one file per directory")
    parser.add_argument("--output-name", default=OUTPUT_NAME,
                        help=f"file name per directory (default: {OUTPUT_NAME})")
    parser.add_argument("--title", default="",
                        help="heading of the collected file (default: name of the first path)")
    parser.add_argument("--no-recursive", dest="recursive", action="store_false",
                        help="do not search subdirectories")
    parser.add_argument("--watch", action="store_true",
                        help="keep watching and re-extract on changes")
    parser.add_argument("--interval", type=float, default=2.0,
                        help="poll interval in seconds for --watch (default: 2)")
    parser.add_argument("--exclude", action="append", default=[],
                        help="glob pattern to skip (can be given more than once)")
    parser.add_argument("--no-default-excludes", action="store_true",
                        help="do not use the default excludes (*/build/*, */out/*)")
    parser.add_argument("--with-author-date", action="store_true",
                        help="additional columns 'Author' and 'Date'")
    parser.add_argument("--max-cell", type=int, default=300,
                        help="truncate quote/note after n characters, 0 = unlimited (default: 300)")
    parser.add_argument("--dry-run", action="store_true",
                        help="only report, write nothing")
    parser.add_argument("--venv", default="",
                        help="path to the Python environment for PyMuPDF "
                             "(otherwise ./.venv next to the script resp. ~/.cache/pdf-annots/venv)")
    parser.add_argument("--no-bootstrap", action="store_true",
                        help="do not install PyMuPDF automatically")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    return parser


def main(argv: "list | None" = None) -> int:
    args = build_parser().parse_args(argv)

    # Line buffering, so the log shows up right away when redirected to a file
    # or when running in the background.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(line_buffering=True)
        except (AttributeError, OSError):
            pass

    paths = [p.expanduser() for p in (list(args.paths) + list(args.root))] or [Path(".")]
    missing = [p for p in paths if not p.exists()]
    if missing:
        for p in missing:
            print(f"path not found: {p}", file=sys.stderr)
        return 2
    args.paths = paths

    defaults = [] if args.no_default_excludes else ["*/build/*", "*/out/*"]
    args.excludes = defaults + args.exclude

    if args.output is not None and str(args.output) != "-":
        args.output = args.output.expanduser()

    ensure_pymupdf(allow_bootstrap=not args.no_bootstrap, explicit_venv=args.venv)

    if args.watch:
        if args.output is not None and str(args.output) == "-":
            print("--watch and '-o -' are mutually exclusive", file=sys.stderr)
            return 2
        try:
            watch(args)
        except KeyboardInterrupt:
            print(f"\n[{stamp()}] stopped")
        return 0

    return process(args)


if __name__ == "__main__":
    sys.exit(main())
